// Generated by CoffeeScript 1.3.3
(function() {
  var Break, Instrument, Player, Tune, btc, instrument_sounds, playSound;

  this.btc = {};

  btc = this.btc;

  instrument_sounds = {};

  playSound = function(instrument) {
    var audio, prefix, sound, source;
    if (!(instrument_sounds[instrument] != null)) {
      audio = document.createElement("audio");
      source = document.createElement("source");
      prefix = 'sounds/' + instrument;
      if (audio.canPlayType('audio/mpeg;')) {
        source.type = 'audio/mpeg';
        source.src = prefix + '.mp3';
      } else {
        source.type = 'audio/ogg';
        source.src = prefix + '.ogg';
      }
      audio.appendChild(source);
      instrument_sounds[instrument] = audio;
    }
    sound = instrument_sounds[instrument];
    if (!sound.paused) {
      sound.pause();
      sound.currentTime = 0.0;
    }
    return sound.play();
  };

  Tune = (function() {

    function Tune(data) {
      var break_, key, val, _ref;
      this.name = data.name;
      this.bars = data.bars;
      this.measure = data.measure;
      this.length = data.length;
      this.breaks = {};
      _ref = data.breaks;
      for (key in _ref) {
        val = _ref[key];
        break_ = new Break(data.breaks[key]);
        this.breaks[break_.name] = break_;
      }
    }

    Tune.prototype.get_break = function(name) {
      return this.breaks[name];
    };

    Tune.prototype.get_all_instruments = function() {
      var instrument, instrument_vals, instruments, name, val, _i, _len, _ref;
      instruments = {};
      _ref = this.breaks['Groove'].get_instruments();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        instrument = _ref[_i];
        instruments[instrument.name] = instrument;
      }
      instrument_vals = [];
      for (name in instruments) {
        val = instruments[name];
        instrument_vals.push(val);
      }
      return instrument_vals;
    };

    return Tune;

  })();

  Break = (function() {

    function Break(data) {
      var name, voices, _ref;
      this.name = data.name;
      this.length = data.length;
      this.solo = data.solo;
      this.instruments = [];
      _ref = data.instruments;
      for (name in _ref) {
        voices = _ref[name];
        this.instruments.push(new Instrument(name, voices));
      }
    }

    Break.prototype.get_instruments = function() {
      return this.instruments;
    };

    return Break;

  })();

  Instrument = (function() {

    function Instrument(name, voices) {
      var time, times, titles, voice, _i, _len;
      this.name = name;
      titles = {
        surdo_low: "Low Surdo",
        surdo_mid: "Mid Surdo",
        surdo_high: "High Surdo",
        surdo: "All Surdos",
        other: "All others"
      };
      if (this.name in titles) {
        this.title = titles[this.name];
      } else {
        this.title = this.name.substr(0, 1).toUpperCase() + this.name.substr(1);
      }
      this._notes = [];
      for (voice in voices) {
        times = voices[voice];
        for (_i = 0, _len = times.length; _i < _len; _i++) {
          time = times[_i];
          this._notes.push({
            'voice': voice,
            'time': time
          });
        }
      }
      this._notes.sort(function(left, right) {
        return left.time - right.time;
      });
      this.reset();
    }

    Instrument.prototype.reset = function() {
      return this._pos = 0;
    };

    Instrument.prototype.peek = function() {
      if (this._pos < this._notes.length) {
        return this._notes[this._pos];
      } else {
        return void 0;
      }
    };

    Instrument.prototype.pop = function() {
      var ret;
      ret = this._pos < this._notes.length ? this._notes[this._pos] : void 0;
      return this._pos += 1;
    };

    Instrument.prototype.get_notes = function() {
      return this._notes;
    };

    return Instrument;

  })();

  Player = (function() {

    function Player() {
      var date, startstop, tune, _i, _len, _ref,
        _this = this;
      this.tunes = [funk, afoxe, custard];
      _ref = this.tunes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tune = _ref[_i];
        $('#tune').append($('<option>', {
          value: tune.name
        }).text(tune.name));
      }
      $('#tune').change(function() {
        return _this.change_tune($('#tune').val());
      });
      this.change_tune("Funk");
      this.change_break("Groove");
      this.bpm = 120;
      this.step = 20;
      this.running = false;
      date = new Date();
      this.ticks = 0;
      this.last_ticks = date.getTime();
      startstop = function() {
        _this.toggle_running();
        if (_this.running) {
          $("#start").hide();
          return $("#stop").show();
        } else {
          $("#start").show();
          return $("#stop").hide();
        }
      };
      $("#start").click(startstop);
      $("#stop").click(startstop);
      $("#stop").hide();
      $("#bpm").val(this.bpm);
      $("#bpm").change(function() {
        return _this.bpm = $("#bpm").val();
      });
      this.restart();
    }

    Player.prototype.restart = function() {
      return this._restart = true;
    };

    Player.prototype.change_tune = function(tune_name) {
      var key, tune, value, _i, _len, _ref, _ref1,
        _this = this;
      _ref = this.tunes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tune = _ref[_i];
        if (tune.name === tune_name) {
          this.tune = new Tune(tune);
          break;
        }
      }
      $('#break').children().remove();
      _ref1 = this.tune.breaks;
      for (key in _ref1) {
        value = _ref1[key];
        $('#break').append($('<option>', {
          value: key
        }).text(key));
      }
      $('#break').change(function() {
        return _this.change_break($('#break').val());
      });
      this.change_break('Groove');
      return this.restart();
    };

    Player.prototype.change_break = function(thabreak_name) {
      this["break"] = this.tune.get_break(thabreak_name);
      this._draw_notes();
      return this.restart;
    };

    Player.prototype._draw_notes = function() {
      var base, clone, instrument, last_time, note, note_node, note_width, notes, root, symbol, symbols, _i, _len, _ref, _results;
      root = $("#instruments");
      base = root.children("#instrument");
      base.hide();
      root.children(".instrument:visible").empty().remove();
      _ref = this["break"].get_instruments();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        instrument = _ref[_i];
        clone = base.clone();
        $(clone).children('.instrument-name').html(instrument.title);
        clone.attr('id', "instrument_" + instrument.name);
        $(clone).show();
        $("#instrument").after(clone);
        last_time = 0;
        note_width = 2;
        notes = $(clone).children('.instrument-notes');
        _results.push((function() {
          var _j, _len1, _ref1, _results1;
          _ref1 = instrument.get_notes();
          _results1 = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            note = _ref1[_j];
            symbols = {
              beat: 'x',
              shadow: '.',
              dampened: 'O'
            };
            if (note.voice in symbols) {
              symbol = symbols[note.voice];
            } else {
              symbol = note.voice.substr(0, 1);
            }
            note_node = $('<div class="instrument-note" style="margin-left:' + (note.time - last_time - (last_time > 0 ? note_width : 0)) + 'em; width:' + note_width + 'em' + '" id=' + ("instrument_" + instrument.name + "_note_" + note.voice + "_" + note.time) + '>' + symbol + '</div>');
            last_time = note.time;
            _results1.push(notes.append(note_node));
          }
          return _results1;
        })());
      }
      return _results;
    };

    Player.prototype.toggle_running = function() {
      this.running = !this.running;
      if (this.running) {
        return this.loop();
      }
    };

    Player.prototype.loop = function() {
      var _this = this;
      if (this.running) {
        setTimeout((function() {
          return _this.loop();
        }), this.step);
      }
      return this._tick();
    };

    Player.prototype._restart_init = function() {
      var instrument, _i, _len, _ref;
      _ref = this["break"].get_instruments();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        instrument = _ref[_i];
        instrument.reset();
      }
      this.time = 1;
      this.last_time = 0;
      this._restart = false;
      return this._draw_notes();
    };

    Player.prototype._tick = function() {
      var date, i, instrument, length, peek, tick_diff, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3, _ref4;
      date = new Date();
      this.ticks = date.getTime();
      tick_diff = this.ticks - this.last_ticks;
      this.last_ticks = this.ticks;
      this.time += tick_diff / 1000.0 * this.bpm / 60.0 * this.tune.measure;
      $('#bar').css('margin-left', this.time + 6.5 + 'em');
      if (Math.floor(this.time) > Math.floor(this.last_time)) {
        this.last_time = this.time;
      }
      length = this["break"].length || this.tune.length;
      if (this.time >= this.tune.measure * this.tune.bars * length + 1) {
        this.restart();
      }
      _ref = this["break"].get_instruments();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        instrument = _ref[_i];
        if (instrument.peek() && this.time >= instrument.peek().time) {
          peek = instrument.peek();
          $("#instrument_" + instrument.name + "_note_" + peek.voice + "_" + peek.time).css('color', 'red');
          if (instrument.name === 'everyone') {
            _ref1 = this.tune.get_all_instruments();
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              i = _ref1[_j];
              if (!((_ref2 = i.name) === 'shaker')) {
                playSound("" + i.name + "_beat");
              }
            }
          } else if (instrument.name === 'others') {
            _ref3 = this.tune.get_all_instruments();
            for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
              i = _ref3[_k];
              if (!((_ref4 = i.name) === this["break"].solo || _ref4 === 'shaker')) {
                playSound("" + i.name + "_beat");
              }
            }
          } else {
            playSound("" + instrument.name + "_" + peek.voice);
          }
          instrument.pop();
        }
      }
      if (this._restart) {
        return this._restart_init();
      }
    };

    return Player;

  })();

  $(document).ready(function() {
    var player;
    return player = new Player();
  });

}).call(this);
